name = "fortune-telling-api"
main = "src/index.ts"
compatibility_date = "2024-05-01"

[build]
command = "npm run build"

[env.development.vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"
# DEEPSEEK_API_KEY = "your-deepseek-api-key-here"

# KV namespaces for production
[[env.production.kv_namespaces]]
binding = "FORTUNE_KV"
# id = "your-kv-namespace-id-here"

# KV namespaces for development
[[env.development.kv_namespaces]]
binding = "FORTUNE_KV"
# id = "your-dev-kv-namespace-id-here"

# Rate limiting (requests per minute)
[vars]
RATE_LIMIT = "60"

